<?php
/**
 * User: 周星
 * Date: 2019/11/4
 * Time: 16:52
 * Email: zhouxing@benbang.com
 */

namespace app\manage\controller;

use app\common\controller\AdminBase;
use util\ErrorCode;
use util\ReqResp;

class AppletConfig extends AdminBase {
    
    public function initialize () {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index () {
        $data = getAppletConfig();
        $this->assign('data', json_encode($data));
        return $this->fetch();
    }

    public function doSave () {
        try {
            $params = input('post.', null);
            if (!$params) {
                throw new \Exception('请填写内容', ErrorCode::PARAMS_ERROR);
            }
            $where = [];
            if (isset($params['applet_id']) && $params['applet_id'] != -1) {
                $where = [
                    'applet_id' => $params['applet_id'],
                ];
            } else {
                unset($params['applet_id']);
            }

            // 数据验证
            $result = $this->validate($params,'common/AppletConfig');
            if(true !== $result){
                throw new \Exception($result, ErrorCode::SUBMIT_PARAMS_VALIDATE_ERROR);
            }

            $res = app()->model('common/AppletConfig')->allowField(true)->save($params, $where);
            if ($res) {
                ReqResp::outputSuccess([], '提交成功');
            }

            throw new \Exception('提交失败', ErrorCode::ACTION_FAILED);
        } catch (\Exception $e) {
            ReqResp::outputFail($e);
        }
    }
}